## 测试
* 我们初始化创建项目的时候就会自动生成一个带有测试函数的测试模块
* `cargo new test-demo --lib`

###  执行测试
* cargo test 执行测试
* `#[test]标注：它将当前的函数标记为一个测试，并使该函数可以在测试运行过程中被识别出来。`
```rust
pub fn add(left: usize, right: usize) -> usize {
    left + right
}

#[cfg(test)]
mod tests {
    use super::*;
    // #[test]标注：它将当前的函数标记为一个测试，并使该函数可以在测试运行过程中被识别出来。
    #[test]
    fn it_works() {
        let result = add(2, 2);
        assert_eq!(result, 4);
    }
}
```

* `在Rust中，一旦测试函数触发panic，该测试就被视作执行失败。`
* `每个测试在运行时都处于独立的线程中，主线程在监视测试线程时，一旦发现测试线程意外终止，就会将对应的测试标记为失败。`

#### 测试错误
```rust
pub fn add(left: usize, right: usize) -> usize {
    left + right
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        let result = add(2, 2);
        assert_eq!(result, 4);
    }

    #[test]
    fn other() {
        // thread 'tests::other' panicked at 'err', src/lib.rs:17:9
        panic!("err")
    }

    #[test]
    fn fail() {
        let result = add(2, 2);
        assert_eq!(result, 5);
        /*
        thread 'tests::fail' panicked at 'assertion failed: `(left == right)`
          left: `4`,
         right: `5`', src/lib.rs:22:9
        */
    }
}
```

#### 使用assert!宏检查结果
* assert! 宏由标准库提供，它可以确保测试中某些条件的值为true。
* assert! 宏可以接收一个能够被计算为布尔类型的值作为参数。
* 当这个值为true时，assert! 宏什么都不用做并正常通过测试。
* 而当值为false时，assert! 宏就会调用panic! 宏，进而导致测试失败。
* 看一个实际的代码例子
```rust
#[derive(Debug)]
pub struct Rectangle {
    length: u32,
    width: u32,
}

impl Rectangle {
    pub fn can_hold(&self, other: &Rectangle) -> bool {
        self.length > other.length && self.width > other.width
    }
}


#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn larger_can_hold_smaller() {
        let larger = Rectangle { length: 8, width: 7 };
        let smaller = Rectangle { length: 5, width: 1 };

        assert!(larger.can_hold(&smaller));
    }
}
```

#### 使用assert_eq! 宏和assert_ne! 宏判断相等性
* `assert_eq! 和assert_ne!。这两个宏分别用于比较并断言两个参数相等或不相等。`
```rust
pub fn add_two(a: i32) -> i32 {
    a + 2
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_adds_two() {
        // 4==4,所以测试通过
        // assert_eq!(4, add_two(2));
        // 5!==4, 所以测试通过
        assert_ne!(5,add_two(2));
    }
}
```

#### 自定义错误信息
```rust
pub fn greeting(name: &str) -> String {
    format!("Hello")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn greeting_contains_name() {
        let result = greeting("Carol");
        // 报错 thread 'tests::greeting_contains_name' panicked at 'Greeting did not contain name, value was `Hello`', src/lib.rs:12:9
        assert!(
            result.contains("Carol"),
            "Greeting did not contain name, value was `{}`", result
        );
    }
}
```

#### 使用should_panic检查panic
* `should_panic。标记了这个属性的测试函数会在代码发生panic时顺利通过，而在代码不发生panic时执行失败。`
```rust
pub struct Guess {
    value: u32,
}

impl Guess {
    pub fn new(value: u32) -> Guess {
        if value < 1 || value > 100 {
            panic!("Guess value must be between 1 and 100, got {}.", value);
        }

        Guess {
            value
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[should_panic]
    fn greater_than_100() {
        // 正常
        // Guess::new(200);

        // 报错
        // failures:
        //     tests::greater_than_100
        Guess::new(11);
    }
}
```
* 测试某个条件会触发带有特定错误提示信息的panic!
```rust
// --略--

impl Guess {
    pub fn new(value: u32) -> Guess {
        if value < 1 {
            panic!("Guess value must be greater than or equal to 1, got {}.",
                   value);
        } else if value > 100 {
            panic!("Guess value must be less than or equal to 100, got {}.",
                   value);
        }

        Guess {
            value
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[should_panic(expected = "Guess value must be less than or equal to 100")]
    fn greater_than_100() {
        // 通过
        // Guess::new(200);

        // 错误 error[E0433]: failed to resolve: use of undeclared type `Guess`
        // Guess::new(10);

        // 错误 error[E0433]: failed to resolve: use of undeclared type `Guess`
        Guess::new(0);
    }
}
```
* `错误提示panic!的提示消息包含#[should_panic(expected = "Guess value must be less than or equal to 100")]`
* 只要包含了就测试通过！

#### 使用Result<T,E>编写测试
* `可以在运行失败时返回一个Err值而不是panic`
```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() -> Result<(), String> {
        if 2 + 2 == 8 {
            Ok(())
        } else {
            // 错误提示 Error: "two plus two does not equal four"
            Err(String::from("two plus two does not equal four"))
        }
    }
}
```

### 控制测试的运行方式
* cargo test同样会在测试模式下编译代码，并运行生成的测试二进制文件。
* 你可以通过指定命令行参数来改变cargo test的默认行为。
---
* 我们既可以为cargo test指定命令行参数，也可以为生成的测试二进制文件指定参数。
* 为了区分两种不同类型的参数，你需要在传递给cargo test的参数后使用分隔符--，并在其后指定需要传递给测试二进制文件的参数。
* 例如，运行cargo test --help会显示出cargo test的可用参数，而运行cargo test -- --help则会显示出所有可以用在--之后的参数。

#### 并行或者串行地进行测试
* 当你尝试运行多个测试时，Rust会默认使用多线程来并行执行它们。
* 这样可以让测试更快地运行完毕，从而尽早得到代码是否能正常工作的反馈。
* 但由于测试是同时进行的，所以开发者必须保证测试之间不会互相依赖，或者依赖到同一个共享的状态或环境上，例如当前工作目录、环境变量等。
---
* 如果你不想并行运行测试，或者希望精确地控制测试时所启动的线程数量，
* `那么可以通过给测试二进制文件传入--test-threads标记及期望的具体线程数量来控制这一行为。`,来看下面的例子：
```text
cargo test -- --test-threads=1
```
* 线程数为1，也就是串行了

#### 显示函数输出
* 希望在cargo test中显示打印的值
```text
cargo test -- --nocapture
```

#### 只针对特定名称的测试
* `cargo test add, 只测试add函数，或者名称的一部分包含add`

#### 通过显式指定来忽略某些测试
* 使用ignore来标记某些耗时的测试，将这些测试排除在正常的测试运行之外
```rust
#[test]
fn it_works() {
    assert_eq!(2 + 2, 4);
}

#[test]
#[ignore]
fn expensive_test() {
    // 需要运行一个小时的代码
}
```
* `我们可以使用cargo test -- --ignored来单独运行这些被忽略的测试：`


### 单元测试
* `在tests模块上标注#[cfg(test)]可以让Rust只在执行cargo test命令时编译和运行该部分测试代码，`
* `而在执行cargo build时剔除它们。这样就可以在正常编译时不包含测试代码，从而节省编译时间和产出物所占用的空间。`







